; PlatformIO Project Configuration File

[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
upload_speed = 460800
board_upload.flash_size = 2MB
platform_packages =
    toolchain-riscv32-esp@15.2.0+20251204
